use crate::{
    configuration::defaults::{
        DEFAULT_AUTO_STARTED_IDLE_TIMEOUT_SECS, DEFAULT_CLIENT_WINDOW_HEIGHT_PX,
        DEFAULT_CLIENT_WINDOW_WIDTH_PX, DEFAULT_CURSOR_VISIBLE,
        DEFAULT_DWIM_HALF_HEIGHT_ASPECT_RATIO, DEFAULT_DWIM_HALF_HEIGHT_MAX_PX,
        DEFAULT_DWIM_WIDE_ASPECT_RATIO, DEFAULT_EDITOR_BACKGROUND_COLOR, DEFAULT_EDITOR_TEXT_COLOR,
        DEFAULT_LINE_HEIGHT_PX, DEFAULT_SELECTION_COLOR,
    },
    documentation::SettingDescriptor,
};

pub fn builtin_setting_descriptors() -> Vec<SettingDescriptor> {
    vec![
        setting(
            "editor.background_color",
            "Editor Background Color",
            "Background color used for editor scenes.",
            "u32 RGB hex",
            &format!("0x{DEFAULT_EDITOR_BACKGROUND_COLOR:06x}"),
            &["Any 24-bit RGB value"],
            &["editor.set({ backgroundColor: 0x1e1e2e })"],
            &["future init.js API", "YAML loaded explicitly by init.js"],
            "applies to newly generated scene updates",
        ),
        setting(
            "editor.cursor_visible",
            "Cursor Visible",
            "Whether the editor cursor is shown by default.",
            "bool",
            if DEFAULT_CURSOR_VISIBLE {
                "true"
            } else {
                "false"
            },
            &["true", "false"],
            &["editor.set({ cursorVisible: true })"],
            &["future init.js API", "YAML loaded explicitly by init.js"],
            "applies to newly generated scene updates",
        ),
        setting(
            "editor.text_color",
            "Editor Text Color",
            "Default text color used by the native editor surface.",
            "u32 RGB hex",
            &format!("0x{DEFAULT_EDITOR_TEXT_COLOR:06x}"),
            &["Any 24-bit RGB value"],
            &["editor.set({ textColor: 0xcdd6f4 })"],
            &["future init.js API", "YAML loaded explicitly by init.js"],
            "requires repaint; runtime application is future work",
        ),
        setting(
            "editor.selection_color",
            "Selection Color",
            "Default selected-text highlight color.",
            "u32 RGB hex",
            &format!("0x{DEFAULT_SELECTION_COLOR:06x}"),
            &["Any 24-bit RGB value"],
            &["editor.set({ selectionColor: 0x3b4261 })"],
            &["future init.js API", "YAML loaded explicitly by init.js"],
            "requires repaint; runtime application is future work",
        ),
        setting(
            "ui.line_height_px",
            "Editor Line Height",
            "Native editor line height in pixels.",
            "f32 pixels",
            &DEFAULT_LINE_HEIGHT_PX.to_string(),
            &["Positive pixel value"],
            &["editor.set({ lineHeightPx: 22 })"],
            &["future init.js API", "YAML loaded explicitly by init.js"],
            "applies when editor views are created or re-rendered",
        ),
        setting(
            "client.window_width_px",
            "Client Window Width",
            "Default client window width in pixels.",
            "u64 pixels",
            &DEFAULT_CLIENT_WINDOW_WIDTH_PX.to_string(),
            &["Positive integer pixels"],
            &["editor.set({ windowWidthPx: 900 })"],
            &["future init.js API", "YAML loaded explicitly by init.js"],
            "applies when a client window is opened",
        ),
        setting(
            "client.window_height_px",
            "Client Window Height",
            "Default client window height in pixels.",
            "u64 pixels",
            &DEFAULT_CLIENT_WINDOW_HEIGHT_PX.to_string(),
            &["Positive integer pixels"],
            &["editor.set({ windowHeightPx: 600 })"],
            &["future init.js API", "YAML loaded explicitly by init.js"],
            "applies when a client window is opened",
        ),
        setting(
            "server.idle_timeout_secs",
            "Server Idle Timeout",
            "When no clients remain, an explicitly started server exits after this timeout when configured.",
            "Option<u64>",
            "None for explicit `st server`",
            &["None", "Any non-negative integer seconds"],
            &[
                "st server --idle-timeout-secs 300",
                "st server --no-idle-timeout",
            ],
            &[
                "CLI flag --idle-timeout-secs",
                "CLI flag --no-idle-timeout",
                "future init.js API",
            ],
            "requires server restart until runtime config reload exists",
        ),
        setting(
            "server.auto_start_idle_timeout_secs",
            "Auto-start Server Idle Timeout",
            "Idle timeout used when a client auto-starts the server.",
            "u64 seconds",
            &DEFAULT_AUTO_STARTED_IDLE_TIMEOUT_SECS.to_string(),
            &["Any non-negative integer seconds"],
            &["config.set('server.auto_start_idle_timeout_secs', 300)"],
            &["future init.js API", "YAML loaded explicitly by init.js"],
            "applies before auto-starting a server process",
        ),
        setting(
            "paths.runtime_dir",
            "Runtime Directory",
            "Directory containing runtime IPC files such as the server socket.",
            "Path",
            "$XDG_RUNTIME_DIR/st or system temporary directory + /st",
            &["Any user-writable directory path"],
            &["ST_RUNTIME_DIR=/tmp/st-runtime st"],
            &[
                "ST_RUNTIME_DIR bootstrap environment variable",
                "future init.js API",
            ],
            "must be known before client/server IPC starts",
        ),
        setting(
            "paths.extension_dirs",
            "Extension Directories",
            "Directories that user configuration may explicitly load extensions from.",
            "Vec<Path>",
            "[]; conventional path ~/.config/st/extensions is not mandatory",
            &["Any readable directory path chosen by the user"],
            &["await extensions.loadDir(\"~/work/editor-extensions\")"],
            &["init.js", "YAML field extension_dirs consumed by init.js"],
            "applies when config/extensions are loaded or reloaded",
        ),
        setting(
            "paths.tool_dirs",
            "Tool Directories",
            "Directories that user configuration may explicitly load tools from.",
            "Vec<Path>",
            "[]; conventional path ~/.config/st/tools is not mandatory",
            &["Any readable directory path chosen by the user"],
            &["await tools.loadDir(\"~/.config/st/tools\")"],
            &["init.js", "YAML field tool_dirs consumed by init.js"],
            "applies when config/tools are loaded or reloaded",
        ),
        setting(
            "keybindings.default_editor_bindings_enabled",
            "Default Editor Keybindings Enabled",
            "Whether built-in GPUI editor keybindings are installed by default before the future keymap registry takes over.",
            "bool",
            "true",
            &["true", "false"],
            &["keymap.defaults({ editor: true })"],
            &["future init.js API", "YAML loaded explicitly by init.js"],
            "applies when a client process starts",
        ),
        setting(
            "window.split_dwim_wide_aspect_ratio",
            "DWIM Wide Window Aspect Ratio",
            "Aspect-ratio threshold where DWIM first chooses a horizontal top/bottom split for a wide full-window layout.",
            "f32 ratio",
            &DEFAULT_DWIM_WIDE_ASPECT_RATIO.to_string(),
            &["Positive ratio greater than half-height threshold"],
            &["editor.set({ splitDwimWideAspectRatio: 1.7 })"],
            &["future init.js API", "YAML loaded explicitly by init.js"],
            "applies to subsequent DWIM split commands",
        ),
        setting(
            "window.split_dwim_half_height_aspect_ratio",
            "DWIM Half-height Vertical Aspect Ratio",
            "Aspect-ratio threshold where DWIM chooses vertical left/right splits for wide but height-constrained windows.",
            "f32 ratio",
            &DEFAULT_DWIM_HALF_HEIGHT_ASPECT_RATIO.to_string(),
            &["Positive ratio below window.split_dwim_wide_aspect_ratio"],
            &["editor.set({ splitDwimHalfHeightAspectRatio: 1.3 })"],
            &["future init.js API", "YAML loaded explicitly by init.js"],
            "applies to subsequent DWIM split commands",
        ),
        setting(
            "window.split_dwim_half_height_max_px",
            "DWIM Half-height Maximum Height",
            "Maximum window height treated as height-constrained for DWIM vertical split preference.",
            "u32 pixels",
            &DEFAULT_DWIM_HALF_HEIGHT_MAX_PX.to_string(),
            &["Positive integer pixels"],
            &["editor.set({ splitDwimHalfHeightMaxPx: 600 })"],
            &["future init.js API", "YAML loaded explicitly by init.js"],
            "applies to subsequent DWIM split commands",
        ),
    ]
}

fn setting(
    id: &str,
    title: &str,
    description: &str,
    value_type: &str,
    default_value: &str,
    valid_values: &[&str],
    examples: &[&str],
    configured_via: &[&str],
    reload_behavior: &str,
) -> SettingDescriptor {
    SettingDescriptor {
        id: id.into(),
        title: title.into(),
        description: description.into(),
        value_type: value_type.into(),
        default_value: default_value.into(),
        valid_values: valid_values.iter().map(|value| (*value).into()).collect(),
        examples: examples.iter().map(|value| (*value).into()).collect(),
        configured_via: configured_via.iter().map(|value| (*value).into()).collect(),
        reload_behavior: reload_behavior.into(),
    }
}
